export const DISCIPLINE_QUOTES = [
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The secret of your future is hidden in your daily routine.", author: "Mike Murdock", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Success isn't always about greatness. It's about consistency. Consistent hard work leads to success.", author: "Dwayne Johnson", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.", author: "John C. Maxwell", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Bruce Lee", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Self-discipline is the ability to make yourself do what you should do, when you should do it, whether you feel like it or not.", author: "Elbert Hubbard", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The price of excellence is discipline. The cost of mediocrity is disappointment.", author: "William Arthur Ward", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Without discipline, there's no life at all.", author: "Katharine Hepburn", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Discipline is the refining fire by which talent becomes ability.", author: "Roy L. Smith", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "No man is free who is not master of himself.", author: "Epictetus", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Rule your mind or it will rule you.", author: "Horace", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The first and best victory is to conquer self.", author: "Plato", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Self-discipline begins with the mastery of your thoughts.", author: "Napoleon Hill", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Talent without discipline is like an octopus on roller skates.", author: "H. Jackson Brown Jr.", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Self-respect is the fruit of discipline; the sense of dignity grows with the ability to say no to oneself.", author: "Abraham Joshua Heschel", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Through discipline comes freedom.", author: "Aristotle", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The pain of discipline is nothing like the pain of disappointment.", author: "Justin Langer", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "If you do not conquer self, you will be conquered by self.", author: "Napoleon Hill", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The ability to discipline yourself to delay gratification in the short term in order to enjoy greater rewards in the long term is the indispensable prerequisite for success.", author: "Brian Tracy", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Discipline is the foundation upon which all success is built. Lack of discipline inevitably leads to failure.", author: "Jim Rohn", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Mental toughness is many things. Its qualities are sacrifice and self-denial.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The fight is won or lost far away from witnesses - behind the lines, in the gym, and out there on the road.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I don't count my sit-ups. I only start counting when it starts hurting.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I am the greatest, I said that even before I knew I was.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "If my mind can conceive it, and my heart can believe it - then I can achieve it.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Impossible is just a big word thrown around by small men.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Only a man who knows what it is like to be defeated can reach down to the bottom of his soul.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "What you're thinking is what you're becoming.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I know where I'm going and I know the truth, and I don't have to be what you want me to be.", author: "Muhammad Ali", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Excellence is not a singular act, but a habit. You are what you repeatedly do.", author: "Shaquille O'Neal", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The only way to prove you are a good sport is to lose.", author: "Ernie Banks", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The difference between the impossible and the possible lies in a person's determination.", author: "Tommy Lasorda", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.", author: "Dan Gable", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Persistence can change failure into extraordinary achievement.", author: "Matt Biondi", category: "DISCIPLINE", tone: "SUPPORTIVE" },
  { text: "The harder you work, the harder it is to surrender.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The quality of a person's life is in direct proportion to their commitment to excellence.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The only place success comes before work is in the dictionary.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Individual commitment to a group effort - that is what makes a team work.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The measure of who we are is what we do with what we have.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Practice does not make perfect. Only perfect practice makes perfect.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The achievements of an organization are the results of the combined effort of each individual.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Confidence is contagious. So is lack of confidence.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Football is like life - it requires perseverance, self-denial, hard work, sacrifice, dedication, and respect for authority.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Once you learn to quit, it becomes a habit.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The spirit, the will to win, and the will to excel are the things that endure.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Show me a guy who's afraid to look bad, and I'll show you a guy you can beat every time.", author: "Lou Brock", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I think goals should never be easy, they should force you to work.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "If you want to be the best, you have to do things that other people aren't willing to do.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I won't predict anything historic. But nothing is impossible.", author: "Michael Phelps", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Records are always made to be broken no matter what they are.", author: "Michael Phelps", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I think that everything is possible as long as you put your mind to it and you put the work and time into it.", author: "Michael Phelps", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "You dream. You plan. You reach. There will be obstacles. There will be doubters. There will be mistakes. But with hard work, with belief, with confidence and trust in yourself and those around you, there are no limits.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I want to test my maximum and see how much I can do. And I want to change the world of swimming.", author: "Michael Phelps", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "So many people along the way, whatever it is you aspire to do, will tell you it can't be done. But it all it takes is imagination.", author: "Michael Phelps", category: "DISCIPLINE", tone: "SUPPORTIVE" },
  { text: "The secret to success is to know something nobody else knows.", author: "Aristotle Onassis", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "DISCIPLINE", tone: "SUPPORTIVE" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.", author: "Jim Rohn", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I never dreamed about success, I worked for it.", author: "Estée Lauder", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Success seems to be connected with action. Successful people keep moving.", author: "Conrad Hilton", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "DISCIPLINE", tone: "SUPPORTIVE" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn", category: "DISCIPLINE", tone: "SUPPORTIVE" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", category: "DISCIPLINE", tone: "EXECUTION" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "DISCIPLINE", tone: "NEUTRAL" },
  { text: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron", category: "DISCIPLINE", tone: "EXECUTION" },
];
