export const ENDURANCE_QUOTES = [
  { text: "The body does not want you to do this. As you run, it tells you to stop but the mind must be strong.", author: "Eliud Kipchoge", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "No human is limited.", author: "Eliud Kipchoge", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The miracle isn't that I finished. The miracle is that I had the courage to start.", author: "John Bingham", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Running is the greatest metaphor for life, because you get out of it what you put into it.", author: "Oprah Winfrey", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The will to win means nothing without the will to prepare.", author: "Juma Ikangaa", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Run when you can, walk if you have to, crawl if you must; just never give up.", author: "Dean Karnazes", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The real purpose of running isn't to win a race, it's to test the limits of the human heart.", author: "Bill Bowerman", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "To give anything less than your best is to sacrifice the gift.", author: "Steve Prefontaine", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "A lot of people run a race to see who is fastest. I run to see who has the most guts.", author: "Steve Prefontaine", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Somebody may beat me, but they are going to have to bleed to do it.", author: "Steve Prefontaine", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The more you sweat in training, the less you bleed in combat.", author: "Richard Marcinko", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "It's not the will to win that matters—everyone has that. It's the will to prepare to win that matters.", author: "Paul Bear Bryant", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "It never gets easier, you just go faster.", author: "Greg LeMond", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Cycling is suffering.", author: "Fausto Coppi", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "As long as I breathe, I attack.", author: "Bernard Hinault", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The race is won by the rider who can suffer the most.", author: "Eddy Merckx", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Ride as much or as little, or as long or as short as you feel. But ride.", author: "Eddy Merckx", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "When my legs hurt, I say: 'Shut up legs! Do what I tell you to do!'", author: "Jens Voigt", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Nothing compares to the simple pleasure of riding a bike.", author: "John F. Kennedy", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Running allows me to set my mind free. Nothing seems impossible.", author: "Kara Goucher", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "The marathon can humble you.", author: "Bill Rodgers", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I always tell people that the marathon is a race of attrition. You have to be patient.", author: "Meb Keflezighi", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Running is my meditation, mind flush, cosmic telephone, mood elevator and spiritual communion.", author: "Lorraine Moller", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Somewhere in the world someone is training when you are not. When you race him, he will win.", author: "Tom Fleming", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The obsession with running is really an obsession with the potential for more and more life.", author: "George Sheehan", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I run because long after my footprints fade away, maybe I will have inspired a few to reject the easy path.", author: "Scott Jurek", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "There is magic in misery. Just ask any runner.", author: "Dean Karnazes", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The human body is capable of amazing physical deeds. If we could just free ourselves from our perceived limitations.", author: "Dean Karnazes", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "I often hear someone say I'm not a real runner. We are all runners, some just run faster than others.", author: "Bart Yasso", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Running is alone time that lets my brain unspool the tangles that build up over days.", author: "Rob Haneisen", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "I've learned that it's what you do with the miles, rather than how many you've run.", author: "Rod DeHaven", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The five S's of sports training are: stamina, speed, strength, skill, and spirit; but the greatest of these is spirit.", author: "Ken Doherty", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I always loved running. It was something you could do by yourself, and under your own power.", author: "Jesse Owens", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I don't run to add days to my life, I run to add life to my days.", author: "Ronald Rook", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "If you want to become the best runner you can be, start now. Don't spend the rest of your life wondering if you can do it.", author: "Priscilla Welch", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Running is a road to self-awareness and reliance.", author: "Doris Brown Heritage", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I run because it's so symbolic of life. You have to drive yourself to overcome the obstacles.", author: "Arthur Blank", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The bicycle is a curious vehicle. Its passenger is its engine.", author: "John Howard", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "When the spirits are low, when the day appears dark, just mount a bicycle and go out for a spin.", author: "Arthur Conan Doyle", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Cycling isn't a game, it's a sport. Tough, hard and unpitying, and it requires great sacrifices.", author: "Jean de Gribaldy", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Melancholy is incompatible with bicycling.", author: "James E. Starrs", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Every time I see an adult on a bicycle, I no longer despair for the future of the human race.", author: "H.G. Wells", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Don't buy upgrades, ride up grades.", author: "Eddy Merckx", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside.", author: "Lance Armstrong", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The bicycle is the most civilized conveyance known to man.", author: "Iris Murdoch", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I'm going to work so that it's a pure guts race at the end, and if it is, I am the only one who can win it.", author: "Steve Prefontaine", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Something inside of me just said 'Hey, wait a minute, I want to beat him,' and I just took off.", author: "Steve Prefontaine", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "It's very hard in the beginning to understand that the whole idea is not to beat the other runners.", author: "George Sheehan", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "I run because if I didn't, I'd be sluggish and glum and spend too much time on the couch.", author: "Bill Clinton", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The only way to define your limits is by going beyond them.", author: "Arthur C. Clarke", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Your body will argue that there is no justifiable reason to continue. Your only recourse is to call on your spirit.", author: "Dean Karnazes", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Most people never run far enough on their first wind to find out they've got a second.", author: "William James", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The long run puts the tiger in the cat.", author: "Bill Squires", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "We run, not because we think it is doing us good, but because we enjoy it and cannot help ourselves.", author: "Roger Bannister", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Ask yourself: 'Can I give more?' The answer is usually: 'Yes.'", author: "Paul Tergat", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Running is about finding your inner peace, and so is a life well lived.", author: "Dean Karnazes", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "I breathe in strength and breathe out weakness.", author: "Amy Hastings", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Every morning in Africa, a gazelle wakes up. It knows it must outrun the fastest lion or it will be killed.", author: "Christopher McDougall", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Good things come slow, especially in distance running.", author: "Bill Dellinger", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "There's not one body type that equates to success. Accept the body you have and be the best you can be with it.", author: "Mary Cullen", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Running well is a matter of having the patience to persevere when we are tired and not expecting instant results.", author: "Robert de Castella", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "I run because it's my passion, and not just a sport. Every time I walk out the door, I know why I'm going where I'm going.", author: "Sasha Azevedo", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The real competition is always between what you've done and what you're capable of doing.", author: "Geoffrey Gaberino", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.", author: "Lou Holtz", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The difference between try and triumph is just a little umph!", author: "Marvin Phillips", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Endurance is not just the ability to bear a hard thing, but to turn it into glory.", author: "William Barclay", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Endurance is one of the most difficult disciplines, but it is to the one who endures that the final victory comes.", author: "Buddha", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Endurance is patience concentrated.", author: "Thomas Carlyle", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The first virtue in a soldier is endurance of fatigue; courage is only the second virtue.", author: "Napoleon Bonaparte", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "What the mind can conceive and believe, it can achieve.", author: "Napoleon Hill", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Whether you think you can, or you think you can't – you're right.", author: "Henry Ford", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "The last three or four reps is what makes the muscle grow.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "For me life is continuously being hungry. The meaning of life is not simply to exist, to survive, but to move ahead.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The worst thing I can be is the same as everybody else. I hate that.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "What we face may look insurmountable. But I learned something from all those years of training and competing. I learned something from all those sets and reps when I didn't think I could lift another ounce of weight.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "You can't climb the ladder of success with your hands in your pockets.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Rivers know this: there is no hurry. We shall get there some day.", author: "A.A. Milne", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", author: "John Quincy Adams", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "By perseverance the snail reached the ark.", author: "Charles Spurgeon", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Perseverance is failing 19 times and succeeding the 20th.", author: "Julie Andrews", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Success is the result of perfection, hard work, learning from failure, loyalty, and persistence.", author: "Colin Powell", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak.", author: "Thomas Carlyle", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Nothing in the world can take the place of persistence.", author: "Calvin Coolidge", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.", author: "Stephen King", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Sometimes life is going to hit you in the head with a brick. Don't lose faith.", author: "Steve Jobs", category: "ENDURANCE", tone: "SUPPORTIVE" },
  { text: "Have the courage to follow your heart and intuition.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "I'm convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "I want to put a ding in the universe.", author: "Steve Jobs", category: "ENDURANCE", tone: "EXECUTION" },
  { text: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
  { text: "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.", author: "Steve Jobs", category: "ENDURANCE", tone: "NEUTRAL" },
];
