export const FOCUS_QUOTES = [
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee", category: "FOCUS", tone: "EXECUTION" },
  { text: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell", category: "FOCUS", tone: "EXECUTION" },
  { text: "Where focus goes, energy flows.", author: "Tony Robbins", category: "FOCUS", tone: "EXECUTION" },
  { text: "The key to success is to focus our conscious mind on things we desire not things we fear.", author: "Brian Tracy", category: "FOCUS", tone: "EXECUTION" },
  { text: "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", author: "Zig Ziglar", category: "FOCUS", tone: "EXECUTION" },
  { text: "You can't depend on your eyes when your imagination is out of focus.", author: "Mark Twain", category: "FOCUS", tone: "NEUTRAL" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "FOCUS", tone: "SUPPORTIVE" },
  { text: "Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it.", author: "Greg Anderson", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Most people have no idea of the giant capacity we can immediately command when we focus all of our resources on mastering a single area of our lives.", author: "Tony Robbins", category: "FOCUS", tone: "EXECUTION" },
  { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey", category: "FOCUS", tone: "EXECUTION" },
  { text: "You don't get results by focusing on results. You get results by focusing on the actions that produce results.", author: "Mike Hawkins", category: "FOCUS", tone: "EXECUTION" },
  { text: "Focus is a matter of deciding what things you're not going to do.", author: "John Carmack", category: "FOCUS", tone: "EXECUTION" },
  { text: "The ability to focus attention on important things is a defining characteristic of intelligence.", author: "Robert J. Shiller", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Always remember, your focus determines your reality.", author: "George Lucas", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Focusing is about saying no.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "People think focus means saying yes to the thing you've got to focus on. But that's not what it means at all. It means saying no to the hundred other good ideas.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "That's been one of my mantras — focus and simplicity.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The art of being wise is the art of knowing what to overlook.", author: "William James", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The shorter way to do many things is to do only one thing at a time.", author: "Mozart", category: "FOCUS", tone: "EXECUTION" },
  { text: "Multitasking is the ability to screw everything up simultaneously.", author: "Jeremy Clarkson", category: "FOCUS", tone: "NEUTRAL" },
  { text: "You can do anything, but not everything.", author: "David Allen", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Beware the barrenness of a busy life.", author: "Socrates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "It is not enough to be busy. So are the ants. The question is: What are we busy about?", author: "Henry David Thoreau", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Action expresses priorities.", author: "Mahatma Gandhi", category: "FOCUS", tone: "EXECUTION" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey", category: "FOCUS", tone: "EXECUTION" },
  { text: "Things which matter most must never be at the mercy of things which matter least.", author: "Johann Wolfgang von Goethe", category: "FOCUS", tone: "EXECUTION" },
  { text: "If you chase two rabbits, you will not catch either one.", author: "Russian Proverb", category: "FOCUS", tone: "EXECUTION" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker", category: "FOCUS", tone: "EXECUTION" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "FOCUS", tone: "EXECUTION" },
  { text: "Vision without execution is hallucination.", author: "Thomas Edison", category: "FOCUS", tone: "EXECUTION" },
  { text: "Ideas are easy. Execution is everything.", author: "John Doerr", category: "FOCUS", tone: "EXECUTION" },
  { text: "Execution is the chariot of genius.", author: "William Blake", category: "FOCUS", tone: "EXECUTION" },
  { text: "A good plan violently executed now is better than a perfect plan executed next week.", author: "George S. Patton", category: "FOCUS", tone: "EXECUTION" },
  { text: "An ounce of action is worth a ton of theory.", author: "Ralph Waldo Emerson", category: "FOCUS", tone: "EXECUTION" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin", category: "FOCUS", tone: "EXECUTION" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I'm convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "I want to put a ding in the universe.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Sometimes life is going to hit you in the head with a brick. Don't lose faith.", author: "Steve Jobs", category: "FOCUS", tone: "SUPPORTIVE" },
  { text: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I think if you do something and it turns out pretty good, then you should go do something else wonderful, not dwell on it for too long.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Details matter, it's worth waiting to get it right.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Great things in business are never done by one person. They're done by a team of people.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "It's really hard to design products by focus groups. A lot of times, people don't know what they want until you show it to them.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I'm as proud of many of the things we haven't done as the things we have done.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "We're here to put a dent in the universe. Otherwise why else even be here?", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "The only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "If you are working on something exciting that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Let's go invent tomorrow rather than worrying about what happened yesterday.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "I think the things you regret most in life are the things you didn't do.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Get closer than ever to your customers. So close that you tell them what they need well before they realize it themselves.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "The ones who are crazy enough to think they can change the world, are the ones that do.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "My job is not to be easy on people. My job is to take these great people we have and to push them and make them even better.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "We don't get a chance to do that many things, and every one should be really excellent.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "I'm actually as proud of the things we haven't done as the things I have done. Innovation is saying no to 1,000 things.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "When you're a carpenter making a beautiful chest of drawers, you're not going to use a piece of plywood on the back.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "What a computer is to me is the most remarkable tool that we have ever come up with. It's the equivalent of a bicycle for our minds.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "We made the buttons on the screen look so good you'll want to lick them.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I would trade all of my technology for an afternoon with Socrates.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The doers are the major thinkers. The people that really create the things that change this industry are both the thinker and doer in one person.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "You've got to start with the customer experience and work back toward the technology, not the other way around.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "Design is a funny word. Some people think design means how it looks. But of course, if you dig deeper, it's really how it works.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I think we're having fun. I think our customers really like our products. And we're always trying to do better.", author: "Steve Jobs", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The cure for Apple is not cost-cutting. The cure for Apple is to innovate its way out of its current predicament.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "It's more fun to be a pirate than to join the navy.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "To turn really interesting ideas and fledgling technologies into a company that can continue to innovate for years, it requires a lot of disciplines.", author: "Steve Jobs", category: "FOCUS", tone: "EXECUTION" },
  { text: "I'm convinced that to give away a dollar effectively is harder than to make a dollar.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "It's fine to celebrate success but it is more important to heed the lessons of failure.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "If you can't make it good, at least make it look good.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Life is not fair; get used to it.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Patience is a key element of success.", author: "Bill Gates", category: "FOCUS", tone: "SUPPORTIVE" },
  { text: "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I really had a lot of dreams when I was a kid, and I think a great deal of that grew out of the fact that I had a chance to read a lot.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "As we look ahead into the next century, leaders will be those who empower others.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "If you think your teacher is tough, wait till you get a boss.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Television is not real life. In real life people actually have to leave the coffee shop and go to jobs.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Be nice to nerds. Chances are you'll end up working for one.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I failed in some subjects in exam, but my friend passed in all. Now he is an engineer in Microsoft and I am the owner of Microsoft.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The Internet is becoming the town square for the global village of tomorrow.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Information technology and business are becoming inextricably interwoven.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The advance of technology is based on making it fit in so that you don't really even notice it.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The vision is really about empowering workers, giving them all the information about what's going on so they can do a lot more than they've done in the past.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Intellectual property has the shelf life of a banana.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "This is a fantastic time to be entering the business world, because business is going to change more in the next 10 years than it has in the last 50.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The PC has improved the world in just about every area you can think of. Amazing developments in communications, collaboration and efficiencies.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I believe that if you show people the problems and you show them the solutions they will be moved to act.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Headlines, in a way, are what mislead you because bad news is a headline, and gradual improvement is not.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Legacy is a stupid thing! I don't want a legacy.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I have been struck again and again by how important measurement is to improving the human condition.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Climate change is a terrible problem, and it absolutely needs to be solved. It deserves to be a huge priority.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The general idea of the rich helping the poor, I think, is important.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Discrimination has a lot of layers that make it tough for minorities to get a leg up.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I'm a great believer that any tool that enhances communication has profound effects in terms of how people can learn from each other.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The world won't care about your self-esteem. The world will expect you to accomplish something before you feel good about yourself.", author: "Bill Gates", category: "FOCUS", tone: "EXECUTION" },
  { text: "Of my mental cycles, I devote maybe 10 percent to business thinking. Business isn't that complicated.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "People always fear change. People feared electricity when it was invented, didn't they?", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Until we're educating every kid in a fantastic way, until every inner city is cleaned up, there is no shortage of things to do.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I was lucky to be involved and get to contribute to something that was important, which is empowering people with software.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Software is a great combination between artistry and engineering.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Whether it's Google or Apple or free software, we've got some fantastic competitors and it keeps us on our toes.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "In terms of doing things I take a fairly scientific approach to why things happen and how they happen.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I do think this next century, hopefully, will be about a more global view. Where you don't just think, 'Yes, my country is doing well,' but you think about the world at large.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Exposure from a young age to the realities of the world is a super-big thing.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I believe in innovation and that the way you get innovation is you fund research and you learn the basic facts.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "The most amazing philanthropists are people who are actually making a significant sacrifice.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Capitalism has worked very well. Anyone who wants to move to North Korea is welcome.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I'm certainly well taken care of in terms of food and clothes.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Money has no utility to me beyond a certain point.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Like my friend Warren Buffett, I feel particularly lucky to do something every day that I love to do. He calls it 'tap-dancing to work.'", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I really had a lot of dreams when I was a kid, and I think a great deal of that grew out of the fact that I had a chance to read a lot.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Reading is still the main way that I both learn new things and test my understanding.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Everyone needs a coach. It doesn't matter whether you're a basketball player, a tennis player, a gymnast or a bridge player.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "We all need people who will give us feedback. That's how we improve.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I believe the returns on investment in the poor are just as exciting as successes achieved in the business arena.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "Effective philanthropy requires a lot of time and creativity - the same kind of focus and skills that building a business requires.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "If geek means you're willing to study things, and if you think science and engineering matter, I plead guilty.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
  { text: "I was a kid who was lucky to have parents who encouraged my interest in science and math.", author: "Bill Gates", category: "FOCUS", tone: "NEUTRAL" },
];
