export const GROWTH_QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.", author: "Mandy Hale", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "GROWTH", tone: "NEUTRAL" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss", category: "GROWTH", tone: "EXECUTION" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Be not afraid of growing slowly, be afraid only of standing still.", author: "Chinese Proverb", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "In any given moment we have two options: to step forward into growth or step back into safety.", author: "Abraham Maslow", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Life is growth. If we stop growing, technically and spiritually, we are as good as dead.", author: "Morihei Ueshiba", category: "GROWTH", tone: "NEUTRAL" },
  { text: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia", category: "GROWTH", tone: "NEUTRAL" },
  { text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Every master was once a disaster.", author: "T. Harv Eker", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "The only thing that is constant is change.", author: "Heraclitus", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn", category: "GROWTH", tone: "NEUTRAL" },
  { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "GROWTH", tone: "NEUTRAL" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", author: "Oprah Winfrey", category: "GROWTH", tone: "NEUTRAL" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl", category: "GROWTH", tone: "NEUTRAL" },
  { text: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsch", category: "GROWTH", tone: "EXECUTION" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson", category: "GROWTH", tone: "EXECUTION" },
  { text: "The biggest room in the world is the room for improvement.", author: "Helmut Schmidt", category: "GROWTH", tone: "NEUTRAL" },
  { text: "It's not about perfect. It's about effort.", author: "Jillian Michaels", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Have no fear of perfection - you'll never reach it.", author: "Salvador Dali", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "The unexamined life is not worth living.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Know thyself.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "True wisdom comes to each of us when we realize how little we understand about life.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy is when men are afraid of the light.", author: "Plato", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The measure of a man is what he does with power.", author: "Plato", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Good actions give strength to ourselves and inspire good actions in others.", author: "Plato", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The beginning is the most important part of the work.", author: "Plato", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Never discourage anyone who continually makes progress, no matter how slow.", author: "Plato", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Courage is knowing what not to fear.", author: "Plato", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The whole is greater than the sum of its parts.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Hope is a waking dream.", author: "Aristotle", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "The aim of art is to represent not the outward appearance of things, but their inward significance.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "What is a friend? A single soul dwelling in two bodies.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The more you know, the more you realize you don't know.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle", category: "GROWTH", tone: "EXECUTION" },
  { text: "We become what we repeatedly do.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The soul never thinks without a picture.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "No great mind has ever existed without a touch of madness.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The worst form of inequality is to try to make unequal things equal.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Those who know, do. Those that understand, teach.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Wishing to be friends is quick work, but friendship is a slow ripening fruit.", author: "Aristotle", category: "GROWTH", tone: "SUPPORTIVE" },
  { text: "The antidote for fifty enemies is one friend.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "A friend to all is a friend to none.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The high-minded man must care more for the truth than for what people think.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Youth is easily deceived because it is quick to hope.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The one exclusive sign of thorough knowledge is the power of teaching.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "All human actions have one or more of these seven causes: chance, nature, compulsion, habit, reason, passion, and desire.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The educated differ from the uneducated as much as the living differ from the dead.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Personal beauty is a greater recommendation than any letter of reference.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Dignity does not consist in possessing honors, but in deserving them.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The law is reason, free from passion.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "All paid jobs absorb and degrade the mind.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Poetry is finer and more philosophical than history; for poetry expresses the universal, and history only the particular.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Man is by nature a social animal.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The ideal man bears the accidents of life with dignity and grace, making the best of circumstances.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "It is not enough to win a war; it is more important to organize the peace.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Fear is pain arising from the anticipation of evil.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The secret to humor is surprise.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Men acquire a particular quality by constantly acting in a particular way.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Character may almost be called the most effective means of persuasion.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "He who has overcome his fears will truly be free.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The least initial deviation from the truth is multiplied later a thousandfold.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "All virtue is summed up in dealing justly.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Republics decline into democracies and democracies degenerate into despotisms.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The gods too are fond of a joke.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Wit is educated insolence.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Poverty is the parent of revolution and crime.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The aim of the wise is not to secure pleasure, but to avoid pain.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The young are permanently in a state resembling intoxication.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Nature does nothing uselessly.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The actuality of thought is life.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Different men seek after happiness in different ways and by different means.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Whosoever is delighted in solitude is either a wild beast or a god.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "At his best, man is the noblest of all animals; separated from law and justice he is the worst.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The wise man does not expose himself needlessly to danger.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "Friendship is essentially a partnership.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
  { text: "The soul is the form of the body.", author: "Aristotle", category: "GROWTH", tone: "NEUTRAL" },
];
