export const MENTAL_TOUGHNESS_QUOTES = [
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "I've missed more than 9000 shots in my career. I've lost almost 300 games. And that is why I succeed.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "When you come to the end of your rope, tie a knot and hang on.", author: "Franklin D. Roosevelt", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", author: "Eleanor Roosevelt", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.", author: "Ambrose Redmoon", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.", author: "Christopher Reeve", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The human spirit is stronger than anything that can happen to it.", author: "C.C. Scott", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Never give in. Never give in. Never, never, never, never.", author: "Winston Churchill", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Courage is resistance to fear, mastery of fear - not absence of fear.", author: "Mark Twain", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "It is not the mountain we conquer but ourselves.", author: "Edmund Hillary", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The brick walls are there for a reason. They're there to give us a chance to show how badly we want something.", author: "Randy Pausch", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "I've always believed that if you put in the work, the results will come.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Limits, like fear, is often an illusion.", author: "Michael Jordan", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The mind is the athlete; the body is simply the means it uses.", author: "Bryce Courtenay", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Sports do not build character. They reveal it.", author: "Heywood Broun", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The principle is competing against yourself. It's about self-improvement.", author: "Steve Young", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "You're never a loser until you quit trying.", author: "Mike Ditka", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "The more difficult the victory, the greater the happiness in winning.", author: "Pele", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "A champion is someone who gets up when he can't.", author: "Jack Dempsey", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The difference between the impossible and the possible lies in a person's determination.", author: "Tommy Lasorda", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Gold medals aren't really made of gold. They're made of sweat, determination, and guts.", author: "Dan Gable", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Persistence can change failure into extraordinary achievement.", author: "Matt Biondi", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Age is no barrier. It's a limitation you put on your mind.", author: "Jackie Joyner-Kersee", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The only way to prove that you're a good sport is to lose.", author: "Ernie Banks", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "A trophy carries dust. Memories last forever.", author: "Mary Lou Retton", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "It's hard to beat a person who never gives up.", author: "Babe Ruth", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "You just can't beat the person who never gives up.", author: "Babe Ruth", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The way a team plays as a whole determines its success.", author: "Babe Ruth", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I think about the business of winning. That's what I do.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Everything negative – pressure, challenges – is all an opportunity for me to rise.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I have self-doubt. I have insecurity. I have fear of failure. But I also have the ability to push through.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I'm reflective only in the sense that I learn to move forward. I reflect with a purpose.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "Pain doesn't tell you when you ought to stop. Pain is the little voice in your head that tries to hold you back.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Use your success, wealth and influence to put them in the best position to realize their own dreams and find their true purpose.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "If you're afraid to fail, then you're probably going to fail.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I don't want to be the next Michael Jordan, I only want to be Kobe Bryant.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The beauty in being blessed with talent is rising above doubters to create something beautiful.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I create my own path. It was straight and narrow. I looked at it this way: you were either in my way or out of it.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "There's nothing truly to be afraid of, when you think about it, because I've failed before, and I woke up the next morning.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Once you know what failure feels like, determination chases success.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Haters are a good problem to have. Nobody hates the good ones. They hate the great ones.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I focus on one thing and one thing only – that's trying to win as many championships as I can.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "We all have self-doubt. You don't deny it, but you also don't capitulate to it. You embrace it.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "I'm here. I'm not going anywhere. No matter what the injury – unless it's completely debilitating – I'm going to be the same player.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The important thing is that your teammates have to know you're pulling for them and you really want them to be successful.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I have nothing in common with lazy people who blame others for their lack of success.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "What I'm doing right now, I'm chasing perfection.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I'll do whatever it takes to win, whether it's sitting on a bench waving a towel or hitting the game-winning shot.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "Trust me, setting things up right from the beginning will avoid a ton of tears and heartache.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "These young guys are playing checkers. I'm out there playing chess.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I can't relate to lazy people. We don't speak the same language. I don't understand you. I don't want to understand you.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The only thing I'm afraid of is bees. I don't like bees. I'm allergic to them.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I'm extremely willful to win, and I respond to challenges.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "My parents are my backbone. Still are. They're the only group that will support you if you score zero or you score 40.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
  { text: "Sports are such a great teacher. I think of everything they've taught me: camaraderie, humility, how to resolve differences.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "The topic of leadership is a touchy one. A lot of leaders fail because they don't have the bravery to touch that nerve.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I don't want to be the next Michael Jordan, I only want to be Kobe Bryant.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "When we are saying this cannot be accomplished, this cannot be done, then we are short-changing ourselves.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I realized that intimidation didn't really exist if you're in the right frame of mind.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "We all can be masters at our craft, but you have to make sacrifices that come along with making that decision.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "The moment you give up, is the moment you let someone else win.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I'm playing against great players, playing against the best in the world. The competition is what I've always wanted.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "We don't quit, we don't cower, we don't run. We endure and conquer.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel, handing a cup of water to a teammate, or hitting the game-winning shot.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "EXECUTION" },
  { text: "I'm not the next Michael Jordan. I'm the first Kobe Bryant.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "NEUTRAL" },
  { text: "I have self-doubt. I have insecurity. I have fear of failure. I have nights when I show up at the arena and I'm like, 'My back hurts, my feet hurt, my knees hurt. I don't have it. I just want to chill.' We all have self-doubt. You don't deny it, but you also don't capitulate to it. You embrace it.", author: "Kobe Bryant", category: "MENTAL_TOUGHNESS", tone: "SUPPORTIVE" },
];
