export const RECOVERY_QUOTES = [
  { text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", author: "Ralph Marston", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Your calm mind is the ultimate weapon against your challenges.", author: "Bryant McGill", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The time to relax is when you don't have time for it.", author: "Sydney J. Harris", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.", author: "Joyce Meyer", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Have patience. All things are difficult before they become easy.", author: "Saadi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Rivers know this: there is no hurry. We shall get there some day.", author: "A.A. Milne", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is the companion of wisdom.", author: "Saint Augustine", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "One moment of patience may ward off great disaster. One moment of impatience may ruin a whole life.", author: "Chinese Proverb", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", author: "John Quincy Adams", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "He that can have patience can have what he will.", author: "Benjamin Franklin", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is not simply the ability to wait - it's how we behave while we're waiting.", author: "Joyce Meyer", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The key to everything is patience. You get the chicken by hatching the egg, not by smashing it.", author: "Arnold H. Glasow", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Genius is eternal patience.", author: "Michelangelo", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is the art of hoping.", author: "Luc de Clapiers", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Learning patience can be a difficult experience, but once conquered, you will find life is easier.", author: "Catherine Pulsifer", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is a virtue, and I'm learning patience. It's a tough lesson.", author: "Elon Musk", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The strongest of all warriors are these two — Time and Patience.", author: "Leo Tolstoy", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "To lose patience is to lose the battle.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Patience is the calm acceptance that things can happen in a different order than the one you have in mind.", author: "David G. Allen", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "All great achievements require time.", author: "Maya Angelou", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Good things come to those who wait.", author: "English Proverb", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Slow and steady wins the race.", author: "Aesop", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Rome wasn't built in a day.", author: "John Heywood", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Rest is not idleness, and to lie sometimes on the grass under trees on a summer's day is by no means a waste of time.", author: "John Lubbock", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Sometimes the most productive thing you can do is relax.", author: "Mark Black", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Sleep is the best meditation.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Don't underestimate the value of doing nothing, of just going along, listening to all the things you can't hear.", author: "A.A. Milne", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Every now and then go away, have a little relaxation, for when you come back to your work your judgment will be surer.", author: "Leonardo da Vinci", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The time you enjoy wasting is not wasted time.", author: "Bertrand Russell", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Calmness is the cradle of power.", author: "Josiah Gilbert Holland", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Within you, there is a stillness and a sanctuary to which you can retreat at any time.", author: "Hermann Hesse", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Prasad Mahes", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Set peace of mind as your highest goal, and organize your life around it.", author: "Brian Tracy", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Inner peace begins the moment you choose not to allow another person or event to control your emotions.", author: "Pema Chödrön", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.", author: "Wayne Dyer", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Do not let the behavior of others destroy your inner peace.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "If you want to conquer the anxiety of life, live in the moment, live in the breath.", author: "Amit Ray", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Stress is caused by being 'here' but wanting to be 'there.'", author: "Eckhart Tolle", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "It's not stress that kills us, it is our reaction to it.", author: "Hans Selye", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The greatest mistake you can make in life is to be continually fearing you will make one.", author: "Elbert Hubbard", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Worry does not empty tomorrow of its sorrow, it empties today of its strength.", author: "Corrie ten Boom", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "You don't have to control your thoughts. You just have to stop letting them control you.", author: "Dan Millman", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.", author: "Oprah Winfrey", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.", author: "Eckhart Tolle", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The ability to be in the present moment is a major component of mental wellness.", author: "Abraham Maslow", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Life is available only in the present moment.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The secret of health for both mind and body is not to mourn for the past, worry about the future, but to live the present moment wisely.", author: "Buddha", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Forever is composed of nows.", author: "Emily Dickinson", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The only time you ever have in which to learn anything or see anything or feel anything is the present moment.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Mindfulness is a way of befriending ourselves and our experience.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The little things? The little moments? They aren't little.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Wherever you go, there you are.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "In today's rush, we all think too much, seek too much, want too much, and forget about the joy of just being.", author: "Eckhart Tolle", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Life is a dance. Mindfulness is witnessing that dance.", author: "Amit Ray", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The best way to capture moments is to pay attention. This is how we cultivate mindfulness.", author: "Jon Kabat-Zinn", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Mindfulness is the aware, balanced acceptance of the present experience.", author: "Sylvia Boorstein", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Be happy in the moment, that's enough. Each moment is all we need, not more.", author: "Mother Teresa", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Walk as if you are kissing the Earth with your feet.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Learn to be calm and you will always be happy.", author: "Paramahansa Yogananda", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", author: "Lao Tzu", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Choose to be optimistic, it feels better.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "My religion is very simple. My religion is kindness.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", author: "Dalai Lama", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "First they ignore you, then they ridicule you, then they fight you, and then you win.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Nobody can hurt me without my permission.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Earth provides enough to satisfy every man's needs, but not every man's greed.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Prayer is not asking. It is a longing of the soul.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "Glory lies in the attempt to reach one's goal and not in reaching it.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
  { text: "I will not let anyone walk through my mind with their dirty feet.", author: "Mahatma Gandhi", category: "RECOVERY", tone: "SUPPORTIVE" },
];
